### ISSUE TITLE
Times out if sid-gen.map is too large

### ISSUE THREAD

**Issue by c08d555e** [cleesmith/uni2espy#1]
With all ETPro and Snort rules loaded in (over 20k) I get this error.  It looks like it could be ES timing out and not uni2espy.  If I lower the sig count it works.  This is the error I receive : 

Loaded 34 classifications.
... standby loading signatures from /etc/snort/rules/gen-msg.map ...
Loaded 314 signatures.
... standby loading signatures from /etc/snort/rules/sid-msg.map ...
Traceback (most recent call last):
  File "./u2e_indexer.py", line 346, in <module>
    msgmap.load_and_index_signature_map(open(os.path.expanduser(args.sidmsgmap_path)))
  File "/root/uni2espy/u2e_sig_class_maps.py", line 241, in load_and_index_signature_map
    chunk_size=self.chunk_size
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 104, in streaming_bulk
    resp = client.bulk(bulk_actions, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 712, in bulk
    params=params, body=self._bulk_body(body))
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 301, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 75, in perform_request
    raise ConnectionTimeout('TIMEOUT', str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='127.0.0.1', port='9200'): Read timed out. (read timeout=10))

**Comment by cleesmith** [comment]
We have over 45,000+ rules in many installations with no problem.
What's in your ```u2e.args``` file ?
What version of elasticsearch and it's ```.yml``` file ?
What's ```pip freeze``` say ?

The error is happening in elasticsearch, what else is going on at that time ?
Questions like this and so on....

**Comment by c08d555e** [comment]
FYI, I ended up resolving this by adding an ES timeout value to line 269 of u2e_indexer.py  : 

es_client = Elasticsearch(host=args.es_host, port=args.es_port, timeout=120, max_retries=0)

**Comment by cleesmith** [comment]
That's not really a resolution, just because it works:
* what's the underlying cause ?
* why would you ever have to wait 2 minutes for elasticsearch ?
* is your elasticsearch a cluster of nodes, as uni2espy was designed for use with a single node

Whats' in ```elasticsearch.yml```:
* set ```bootstrap.mlockall: true```

What's in ```/etc/default/elasticsearch```:
* ```ES_HEAP_SIZE=half_the_servers_memory```
* ```MAX_LOCKED_MEMORY=unlimited```

Have you done ```ulimit -l unlimited``` for the user that's running elasticsearch ?

Without really knowing what's going on in your case, I can't add this to the code ... plus we have 
not experienced this issue.

**Comment by c08d555e** [comment]
That's fine, I just wanted to let you know what worked for me.  Yes, all of
those settings match what I'm using and I'm it's a single ES node.

The sensors are underpowered and don't always fail when importing the
rules, but sometimes must take slightly longer than 60 seconds and fails.
This solution works well for me, but I understand if you don't want to add
it to your code.  I wanted to follow-up so you and others knew in case they
experience similar issues.

**Comment by cleesmith** [comment]
From reviewing the ```elasticsearch-py``` code on github the ```retries``` parameter defaults to ```False``` which is the same as ```0``` ... so that's not a fix.   
Also, the ```timeout``` parameter defaults to ```10``` seconds which is a lifetime in ES.

I don't follow your "sensors are underpowered ..." statement as ```sid-msg.map``` is just a file that's 
read/index at ```"./u2e_indexer.py", line 346```.

It's not helpful to others, or me, if you can't respond with your actual settings in (are they a secret?):
```
u2e.args
elasticsearch.yml
/etc/default/elasticsearch
```
... oh well.
